coderunner/urls.py
from django.conf.urls import patterns, include, url

from . import views
from . import auth

app_name = 'coderunner'
urlpatterns = [
    path('', views.main, name='mainView'),
    path('problems', views.allProblems, name='allProblemsView'),
    path('problems/([A-Z]+)', views.problemDetail, name='problemDetailView'),
    path('problems/judge/([A-Z]+)', views.judgeProblem, name='judgeView'),
    path('submissions', views.submissions, name='submissionsView'),
    path('account', views.account, name='accountView'),

    path('logout', auth.logout_view, name='logoutView'),
    path('login', auth.login_view, name='loginView'),
    path('signup', auth.signup_view, name='signupView'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("spojtools/", include("spojtools.urls")),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),

    # path('<int:question_id>/', views.details, name='details'),
    path('<int:pk>/', views.DetailsView.as_view(), name='details'),
    
    # path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

coderunner/models.py
from django.db import models
from django.contrib.auth.models import User

class Problem(models.Model):
    name = models.CharField(max_length=10, primary_key=True)
    description = models.TextField()
    problemStatement = models.TextField()
    publishedDate = models.DateTimeField()

    javaTemplate = models.TextField()
    pythonTemplate = models.TextField()

    standardInput = models.TextField()
    expectedOutput = models.TextField()

    @staticmethod
    def getSolvedProblems(user):
        """ Returns a set of all problem names solved by the user. """
        solved = Submission.objects.filter(user=user, result='AC')
        solved = solved.values('problem').distinct()
        solved = {s['problem'] for s in solved}
        return solved

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        # TODO: Use reverse() to get the url
        return '/coderunner/problems/%s' % self.name

class Submission(models.Model):
    RESULT_CHOICES = (
        ('AC', 'Answer Correct'),
        ('WA', 'Wrong Answer'),
        ('CE', 'Compilation Error'),
        ('RE', 'Runtime Error'),
        ('TLE', 'Time Limit Exceeded'),
    )
    user = models.ForeignKey(User)
    problem = models.ForeignKey(Problem)
    result = models.CharField(max_length=3, choices=RESULT_CHOICES)
    
    sourceCode = models.TextField()
    language = models.CharField(max_length=20)

    submissionDate = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return '<%s, %s, %s, %s, %s>' % (self.user.username,
            self.problem.name, self.result, self.language,
            self.submissionDate.strftime("%D %T"))

coderunner/views.py
import judge
import languages
import logging
import os
import status

from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from models import Problem, Submission

log = logging.getLogger(__name__)

def main(request):
    return render(request, 'coderunner/main.html')

def account(request):
    if not request.user.is_authenticated():
        return render(request, 'coderunner/main.html')
    
    acSubmissions = Submission.objects.filter(user=request.user, result='AC')
    acSubmissions = acSubmissions.values('problem').distinct()
    numSolves = acSubmissions.count()

    return render(request, 'coderunner/account.html', {'acSubmissions':acSubmissions,
                                            'numSolves':numSolves})

def submissions(request):
    if not request.user.is_authenticated():
        return render(request, 'coderunner/main.html')

    submissions = Submission.objects.filter(user=request.user).order_by('-submissionDate')
    return render(request, 'coderunner/submissions.html', {'submissions':submissions})

def allProblems(request):
    problems = Problem.objects.all().order_by('-publishedDate')
    count = problems.count()

    solvedProblems = set()
    if request.user.is_authenticated():
        solvedProblems = Problem.getSolvedProblems(request.user)

    return render(request, 'coderunner/problems.html', {'problems':problems, 'count':count,
                                            'solvedProblems':solvedProblems})

templates = ['java', 'py']
def problemDetail(request, name):
    problem = Problem.objects.get(name=name)
    if not problem:
        return "Problem %s doesn't exist." % name
    
    problemPath = 'problems/%s/' % name

    sourceDict = {}
    sourceDict[languages.JAVA_EXT] = problem.javaTemplate
    sourceDict[languages.PYTHON_EXT] = problem.pythonTemplate

    # If a submission ID was passed, put that code as the template.
    # TODO: Automatically switch to that language
    sid = request.GET.get('sid')
    if sid:
        submission = Submission.objects.get(id=sid)
        if submission.user == request.user:
            ext = languages.langToExt[submission.language]
            sourceDict[ext] = submission.sourceCode
    
    return render(request, "coderunner/problem.html", {'problem':problem, 'sourceDict':sourceDict})

def judgeProblem(request, name):
    if not request.user.is_authenticated():
        return HttpResponse("Please log in to submit your solution.")

    language = request.POST.get('language')
    sourceCode = request.POST.get('editor')
    problem = Problem.objects.get(name=name)

    inputString = problem.standardInput
    outputString = problem.expectedOutput.replace('\r', '')
    
    result = judge.subprocessJudge(sourceCode, language, inputString, outputString)
    resultTuple = status.resultCodeToText(result)
    
    if resultTuple:
        s = Submission(user=request.user, problem=problem, result=resultTuple[0],
            sourceCode=sourceCode, language=language)
        s.save()
        resultText = resultTuple[1]
        return HttpResponse(resultText)
    else:
        return HttpResponse("Invalid response. Something went wrong!")

coderunner/templates/coderunner/account.html
{% extends "base.html" %}

{% block content %}

Hello {{user}}, you have solved {{numSolves}} problem{{numSolves|pluralize}}.
<br/>
{% for submission in acSubmissions %}
    <br/>
    <a href="{% url 'coderunner:problemDetailView' submission.problem %}">
        {{submission.problem}}
    </a>
{% endfor %}
{% endblock %}

coderunner/templates/coderunner/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Programming Exercises</title>
    {% load static %}
    <link type="text/css" rel="stylesheet" href="{% static 'coderunner/bootstrap/bootstrap.min.css' %}" />
    <link type="text/css" rel="stylesheet" href="{% static 'coderunner/prog.css' %}" />
</head>
<body>
    <div class="row-fluid">
        <div class="span12">
            <h1>
                <a href="{% url mainView %}">Programming Exercises</a>
            </h1>
            <br/>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span2">
            {% if user.is_authenticated %}
                Welcome, {{user.username}} <br/>
                <a href="{% url 'coderunner:logoutView' %}">Logout</a> <br/>
                <a href="{% url 'coderunner:accountView' %}">My Account</a>
            {% endif %}

            {% if not user.is_authenticated %}
                <form id="loginForm" method="post" action="{% url 'coderunner:loginView' %}">
                    {% csrf_token %}
                    Username: <br/>
                    <input type="text" name="username"/>
                    Password: </br>
                    <input type="password" name="password" />
                    <input type="submit" value="Login" />
                </form>
                {% if messages %}
                    {% for message in messages %}
                        <span class="error">{{ message }}</span>
                        <br/>
                    {% endfor %}
                {% endif %}
                <a href="{% url 'coderunner:signupView' %}">Signup</a>
            {% endif %}
            <br/>
            <a href="{% url 'coderunner:submissionsView' %}">View submissions</a>
            <a href="{% url 'coderunner:allProblemsView' %}">View all problems</a>
        </div>

        <div class="span10">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    
</body>
</html>

coderunner/templates/coderunner/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
    </head>
    <body>
        <h2>Login</h2>
        <form method="post">
            <label>
                Username
                <input type="text" name="username" value="{{username}}"/>
                <span style="color: red;">{{usernameError}}</span>
            </label>
            <br/>
            <label>
                Password
                <input type="password" name="password" value="{{password}}"/>
                <span style="color: red;">{{passwordError}}</span>
            </label>
            <br/>
            <div style="color: red;">{{loginError}}</div>
            <input type="submit" />
        </form>
    </body>
</html>

coderunner/templates/coderunner/main.html
{% extends "base.html" %}

{% block content %}

Welcome to Programming Exercises!

{% endblock %}

coderunner/templates/coderunner/problem.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'coderunner/codemirror/codemirror.css' %}" />
<!-- <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script> -->
<script type="text/javascript" src="{% static 'coderunner/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'coderunner/jquery.cookie.js' %}"></script>

<script type="text/javascript" src="{% static 'coderunner/codemirror/codemirror.js' %}"></script>
<script type="text/javascript" src="{% static 'coderunner/codemirror/mode/clike/clike.js' %}"></script>
<script type="text/javascript" src="{% static 'coderunner/codemirror/mode/python/python.js' %}"></script>

<script type="text/javascript" src="{% static 'coderunner/submission.js' %}"></script>

<script type="text/javascript">
    var problemName = '{{problem.name}}';
    sourceDict[JAVA_STR] = '{{ sourceDict.java|escapejs }}';
    sourceDict[PYTHON_STR] = '{{ sourceDict.py|escapejs }}';
</script>

<h2>Problem Name: {{problem.name}}</h2>
<br/>

<b>Description: {{problem.description}}</b>
<br/>

Problem Statement: {{problem.problemStatement}}
<br/>
<br/>
<form id="inputForm" method="post">
    <select id="languageSelector" name="language">
        <option value="Java">Java 6 (1.6.0_24)</option>
        <option value="Python">Python (2.7.3)</option>
    </select>
    <br/>
    <textarea id="editor" name="editor"></textarea>
    <br/>
    <input id="submit" type="submit" value="Submit" />
</form>

<div id="result">
    Result will go here.
</div>
{% endblock %}

coderunner/templates/coderunner/problems.html
{% extends "base.html" %}

{% block content %}

There are {{count}} problems available.
<br/>
<br/>
{% for problem in problems %}
    <a href="{% url 'coderunner:problemDetailView' problem.name %}">{{problem.name}}</a>: <u>{{problem.description}}</u>
    {% if problem.name in solvedProblems %}
        <span class="correct">[solved]</span>
    {% endif %}
    <br/>
    {{problem.problemStatement}}
    <br/>
    <br/>
{% endfor %}

{% endblock %}

coderunner/templates/coderunner/signup.html
<!DOCTYPE html>
<html>
    <head>
        <title>Signup</title>
        {% load static %}
        <link type="text/css" rel="stylesheet" href="{% static 'coderunner/prog.css'%}" />
        <style type="text/css">
            input[type="text"], input[type="password"] {
                width: 130px;
            }
        </style>
    </head>
    <body>
        <h2>Signup</h2>
        <form method="post" action="{% url 'coderunner:signupView' %}">
            {% csrf_token %}
            <label>
                Username
                <input type="text" name="username" value="{{username}}"/>
            </label>
            <br/>
            <label>
                Password
                <input type="password" name="password" value="{{password}}"/>
            </label>
            <br/>
            <label>
                Verify Password
                <input type="password" name="verifyPassword" value="{{verifyPassword}}"/>
            </label>
            <br/>
            <label>
                Email (optional)
                <input type="text" name="email" value="{{email}}"/>
            </label>
            <br/>
            <input type="submit" />
        </form>
        <br/>
        {% if messages %}
            {% for message in messages %}
                <span class="error">{{ message }}</span>
                <br/>
            {% endfor %}
        {% endif %}
        <a href="{% url 'coderunner:mainView' %}">Back to main</a>
    </body>
</html>

coderunner/templates/coderunner/submissions.html
{% extends "base.html" %}

{% block content %}

{% for s in submissions %}
    [{{s.id}}]
    <a href="{% url 'coderunner:problemDetailView' s.problem.name %}?sid={{s.id}}">
        {{s.problem.name}}
    </a>:
    <span class="{{s.result}}">{{s.result}}</span>
    in {{s.language}} on {{s.submissionDate}}
    <br/>
{% empty %}
    You don't have any submissions!
{% endfor %}

{% endblock %}